import { walletApi } from './client'
import type {
  OtpRequestResponse,
  TransferRequest,
  TransferResponse,
  WalletAuthResponse,
  WalletResponse,
  WalletTransaction,
} from '@flopay/api-types'

export const consumerAuthApi = {
  requestOtp: (phone: string) =>
    walletApi.post<OtpRequestResponse>('/api/wallet/auth/otp/request', { phone }).then((r) => r.data),

  verifyOtp: (phone: string, otp: string) =>
    walletApi.post<WalletAuthResponse>('/api/wallet/auth/otp/verify', { phone, otp }).then((r) => r.data),
}

export const walletDataApi = {
  getWallet: () => walletApi.get<WalletResponse>('/api/wallet').then((r) => r.data),

  getTransactions: () =>
    walletApi.get<WalletTransaction[]>('/api/wallet/transactions').then((r) => r.data),

  /** Sandbox demo money — mints from the system ISSUANCE account, no real funds. */
  topUp: (amountMinor: number) =>
    walletApi
      .post<WalletResponse>('/api/wallet/topup', { amountMinor, idempotencyKey: crypto.randomUUID() })
      .then((r) => r.data),
}

export const transferApi = {
  /**
   * The idempotency key is generated by the caller (see SendMoneyScreen), not
   * here — it must stay stable across a retry of the *same* user intent, and a
   * key minted inside this function would be new on every call, defeating the
   * point.
   */
  send: (request: TransferRequest) =>
    walletApi.post<TransferResponse>('/api/wallet/transfers', request).then((r) => r.data),
}
