CREATE TABLE favorite_contact (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    vpa        VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT uq_favorite_contact_user_vpa UNIQUE (user_id, vpa)
);

CREATE INDEX idx_favorite_contact_user ON favorite_contact (user_id);
