-- Baseline: the gateway schema as it already existed under Hibernate's
-- `ddl-auto: update`, now captured explicitly so Flyway — not a JPA mapping
-- change — is what ever alters this schema from here on.
--
-- Column widths and types are written to match Hibernate's own defaults
-- exactly (VARCHAR(255) for unannotated strings, TIMESTAMPTZ for Instant),
-- because `ddl-auto: validate` compares against this schema at every boot and
-- fails startup on any mismatch — a deliberate tripwire, not an oversight.

CREATE TABLE merchants (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_merchants_email UNIQUE (email)
);

CREATE TABLE api_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id          VARCHAR(255) NOT NULL,
    key_secret_hash VARCHAR(255) NOT NULL,
    merchant_id     BIGINT       NOT NULL REFERENCES merchants (id),
    active          BOOLEAN      NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_api_keys_key_id UNIQUE (key_id)
);

CREATE INDEX idx_api_keys_merchant_id ON api_keys (merchant_id);

CREATE TABLE orders (
    id          VARCHAR(255) PRIMARY KEY,
    merchant_id BIGINT       NOT NULL REFERENCES merchants (id),
    amount      BIGINT       NOT NULL,
    currency    VARCHAR(255) NOT NULL,
    receipt     VARCHAR(255),
    status      VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_orders_merchant_id ON orders (merchant_id);

CREATE TABLE payments (
    id             VARCHAR(255) PRIMARY KEY,
    order_id       VARCHAR(255) NOT NULL REFERENCES orders (id),
    method         VARCHAR(255) NOT NULL,
    status         VARCHAR(255) NOT NULL,
    amount         BIGINT       NOT NULL,
    signature      VARCHAR(255),
    failure_reason VARCHAR(255),
    captured_at    TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_payments_order_id ON payments (order_id);

CREATE TABLE refunds (
    id         VARCHAR(255) PRIMARY KEY,
    payment_id VARCHAR(255) NOT NULL REFERENCES payments (id),
    amount     BIGINT       NOT NULL,
    status     VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_refunds_payment_id ON refunds (payment_id);

CREATE TABLE webhook_endpoints (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT       NOT NULL REFERENCES merchants (id),
    url         VARCHAR(255) NOT NULL,
    secret      VARCHAR(255) NOT NULL,
    CONSTRAINT uq_webhook_endpoints_merchant_id UNIQUE (merchant_id)
);

CREATE TABLE webhook_logs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id          BIGINT       NOT NULL,
    event_type           VARCHAR(255) NOT NULL,
    payload              TEXT         NOT NULL,
    delivered            BOOLEAN      NOT NULL,
    attempts             INTEGER      NOT NULL,
    last_response_status INTEGER,
    created_at           TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_webhook_logs_merchant_id ON webhook_logs (merchant_id);
