-- Double-entry ledger. Every balance change in FloPay — a wallet top-up, a P2P
-- transfer, a checkout payment, a settlement run, a refund — is one
-- journal_entry with two or more posting rows, and the postings on an entry
-- must always sum to zero (debits == credits). That single invariant is what
-- makes "no money was created or destroyed" a provable, testable property of
-- the schema instead of a hope about the application code.
--
-- account.balance_minor is a materialised cache, not the source of truth —
-- the true balance is always SUM(credits) - SUM(debits) over posting. The
-- cache exists so reading a balance doesn't mean aggregating the whole
-- posting history, and it is only ever mutated in the same transaction as the
-- postings that justify the change (see LedgerService).

CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- USER and MERCHANT accounts have a real owner_id (a future users.id or
    -- merchants.id). SYSTEM accounts (ISSUANCE, FEES) are not owned by any one
    -- user or merchant, but owner_id is still NOT NULL — a sentinel value of 0
    -- is used for them — specifically so the uniqueness constraint below can
    -- rely on ordinary equality instead of SQL's NULL-is-distinct-from-NULL
    -- semantics, which would silently let duplicate SYSTEM accounts through.
    owner_type    VARCHAR(20)  NOT NULL CHECK (owner_type IN ('USER', 'MERCHANT', 'SYSTEM')),
    owner_id      BIGINT       NOT NULL,

    kind          VARCHAR(20)  NOT NULL
                  CHECK (kind IN ('WALLET', 'SETTLEMENT_PENDING', 'SETTLED', 'ISSUANCE', 'FEES')),
    currency      VARCHAR(3)   NOT NULL DEFAULT 'INR',
    balance_minor BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- ISSUANCE is the one account expected to run negative forever — it is the
    -- system's record of how much value it has ever minted, and every rupee
    -- credited anywhere in the ledger was debited from here first. Every other
    -- account kind (wallets, merchant settlement, fees) must never go negative;
    -- an overdraft there is a bug, not a valid state.
    CONSTRAINT chk_account_balance_non_negative
        CHECK (kind = 'ISSUANCE' OR balance_minor >= 0),

    CONSTRAINT uq_account_owner_kind_currency
        UNIQUE (owner_type, owner_id, kind, currency)
);

CREATE INDEX idx_account_owner ON account (owner_type, owner_id);

CREATE TABLE journal_entry (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The single most important column in this schema. Every caller that can
    -- retry (a flaky client, a webhook redelivery, a double-tapped "Send"
    -- button) must supply the same key on retry, and the UNIQUE constraint
    -- turns that retry into a safe no-op at the database level rather than a
    -- second, duplicate transfer.
    idempotency_key VARCHAR(255) NOT NULL,

    -- Free-text discriminator for reporting (TOPUP, P2P_TRANSFER,
    -- CHECKOUT_PAYMENT, SETTLEMENT, REFUND, ...). Not FK-constrained — this is
    -- a tag, not a relationship.
    kind            VARCHAR(40)  NOT NULL,

    -- Loosely-typed pointer to whatever domain object drove this entry (a
    -- payment id, a P2P transfer id, ...). Which table it points into depends
    -- on `kind`, so — like account.owner_id — it cannot be a single real FK.
    reference_id    VARCHAR(255),

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_journal_entry_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX idx_journal_entry_reference ON journal_entry (reference_id);

CREATE TABLE posting (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id     UUID        NOT NULL REFERENCES journal_entry (id),
    account_id   BIGINT      NOT NULL REFERENCES account (id),
    direction    VARCHAR(6)  NOT NULL CHECK (direction IN ('DEBIT', 'CREDIT')),

    -- Always positive; `direction` carries the sign. A zero-amount posting
    -- would be a no-op that could hide a bug, and a negative amount would
    -- break the balance arithmetic direction already encodes.
    amount_minor BIGINT      NOT NULL CHECK (amount_minor > 0)
);

CREATE INDEX idx_posting_entry_id ON posting (entry_id);
CREATE INDEX idx_posting_account_id ON posting (account_id);

-- Defense in depth for the debits == credits invariant. LedgerService is the
-- only code path that is ever supposed to write to `posting`, and it checks
-- this in application code before committing — but a schema that can only be
-- violated by a bug nobody has written yet is a much weaker guarantee than
-- one the database itself refuses to allow. This is a DEFERRED constraint
-- trigger: it queues once per row written inside a transaction and only
-- actually runs the aggregate check right before COMMIT, so a multi-row
-- journal entry (one INSERT per posting line) is checked as a whole rather
-- than being rejected after its first line.
CREATE OR REPLACE FUNCTION check_journal_entry_balanced() RETURNS TRIGGER AS $$
DECLARE
    affected_entry_id UUID;
    debit_total       BIGINT;
    credit_total      BIGINT;
BEGIN
    affected_entry_id := COALESCE(NEW.entry_id, OLD.entry_id);

    SELECT
        COALESCE(SUM(amount_minor) FILTER (WHERE direction = 'DEBIT'), 0),
        COALESCE(SUM(amount_minor) FILTER (WHERE direction = 'CREDIT'), 0)
    INTO debit_total, credit_total
    FROM posting
    WHERE entry_id = affected_entry_id;

    IF debit_total <> credit_total THEN
        RAISE EXCEPTION
            'journal_entry % is not balanced: debits=% credits=% — refusing to commit',
            affected_entry_id, debit_total, credit_total;
    END IF;

    RETURN NULL; -- result is ignored for AFTER triggers
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_journal_entry_balanced
    AFTER INSERT OR UPDATE OR DELETE ON posting
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION check_journal_entry_balanced();

-- The two system accounts every currency needs before any money can move.
-- owner_id = 0 is the SYSTEM sentinel documented above.
INSERT INTO account (owner_type, owner_id, kind, currency, balance_minor) VALUES
    ('SYSTEM', 0, 'ISSUANCE', 'INR', 0),
    ('SYSTEM', 0, 'FEES',     'INR', 0);
