-- Wallet-app consumer identity: phone-keyed users (no email/password — the
-- wallet app authenticates by phone + OTP, not the merchant dashboard's
-- credential model) and their one-time login codes.

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone        VARCHAR(255) NOT NULL,
    vpa          VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    created_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_users_phone UNIQUE (phone),
    CONSTRAINT uq_users_vpa UNIQUE (vpa)
);

CREATE TABLE otp_challenges (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone      VARCHAR(255) NOT NULL,
    otp_hash   VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    consumed   BOOLEAN      NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_otp_challenges_phone ON otp_challenges (phone);
